name: Build and Deploy containers

on:
  # Always test on pull request
  pull_request: []

  # Deploy on merge to main
  push:
    branches:
      - main

jobs:
  deploy-test-containers:
    runs-on: ubuntu-latest
    name: Build Go Smeagle Container
    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: GHCR Login
        if: (github.event_name != 'pull_request')
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Make Space For Build
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Pull Docker Layers
        run: docker pull ghcr.io/vsoch/gosmeagle || exit 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build & Deploy ${{ matrix.dockerfile[1] }}
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          platforms: 'linux/amd64,linux/ppc64le,linux/arm64'
          tags: ghcr.io/vsoch/gosmeagle

      - name: Derive Version
        run: |
            version=$(docker run ghcr.io/vsoch/gosmeagle version)
            printf "Found version ${version}"
            docker tag ghcr.io/vsoch/gosmeagle:latest ghcr.io/vsoch/gosmeagle:${version}
            echo "version=${version}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: 'linux/amd64,linux/ppc64le,linux/arm64'
          push: (github.event_name != 'pull_request')
          tags: |
            ghcr.io/vsoch/gosmeagle:latest
            ghcr.io/vsoch/gosmeagle:${{ env.version }}           
